version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dailyexp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dailyexp"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: bash -c "python -m app.models.init_db && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/dailyexp
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 